{{- if .Values.bot.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bingus.fullname" . }}-bot
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "bingus.bot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.bot.replicaCount }}
  selector:
    matchLabels:
      {{- include "bingus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: bot
  template:
    metadata:
      labels:
        {{- include "bingus.bot.labels" . | nindent 8 }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: bot
          image: {{ include "bingus.image" (dict "repository" .Values.bot.image.repository "tag" .Values.bot.image.tag "Chart" .Chart "Values" .Values) }}
          imagePullPolicy: {{ .Values.bot.image.pullPolicy }}
          env:
            {{- if .Values.bot.config.extraEnv }}
            {{- range $key, $value := .Values.bot.config.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "bingus.fullname" . }}-bot-config
          resources:
            {{- toYaml .Values.bot.resources | nindent 12 }}
          {{- if .Values.bot.probes.liveness.enabled }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "pgrep -f node > /dev/null"
            initialDelaySeconds: {{ .Values.bot.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.bot.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.bot.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.bot.probes.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.bot.probes.readiness.enabled }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "pgrep -f node > /dev/null"
            initialDelaySeconds: {{ .Values.bot.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.bot.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.bot.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.bot.probes.readiness.failureThreshold }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
