{{- if .Values.api.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bingus.fullname" . }}-api-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "bingus.api.labels" . | nindent 4 }}
data:
  # .NET API configuration (environment variables)
  ASPNETCORE_ENVIRONMENT: {{ .Values.api.config.aspnetcoreEnvironment | quote }}
  ASPNETCORE_URLS: {{ .Values.api.config.aspnetcoreUrls | quote }}

  # Service URLs
  ENCODER_URL: {{ .Values.api.config.encoderUrl | quote }}

  # Logging
  Logging__LogLevel__Default: {{ .Values.api.config.logLevel | quote }}

  {{- if .Values.api.config.extraEnv }}
  # Additional environment variables
  {{- range $key, $value := .Values.api.config.extraEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}

  # JSON Configuration Files with smart defaults
  # Falls back to actual config files when Helm values are not specified

  {{- $defaultAppSettings := .Files.Get "configs/appsettings.json" | fromJson }}
  {{- $defaultBingusConfig := .Files.Get "configs/bingus_config.json" | fromJson }}

  appsettings.json: |
    {{- $appSettings := dict }}
    {{- $_ := set $appSettings "Logging" (dict "LogLevel" (dict "Default" (.Values.api.config.logLevel | default $defaultAppSettings.Logging.LogLevel.Default) "Microsoft.AspNetCore" "Warning")) }}
    {{- $_ := set $appSettings "AllowedHosts" "*" }}
    {{- $rateLimiting := dict }}
    {{- $_ := set $rateLimiting "EnableEndpointRateLimiting" (.Values.api.config.rateLimiting.enabled | default $defaultAppSettings.IpRateLimiting.EnableEndpointRateLimiting) }}
    {{- $_ := set $rateLimiting "StackBlockedRequests" false }}
    {{- $_ := set $rateLimiting "RealIpHeader" "X-Forwarded-For" }}
    {{- $_ := set $rateLimiting "ClientIdHeader" "X-ClientId" }}
    {{- $_ := set $rateLimiting "HttpStatusCode" 429 }}
    {{- $_ := set $rateLimiting "IpWhitelist" (.Values.api.config.rateLimiting.ipWhitelist | default $defaultAppSettings.IpRateLimiting.IpWhitelist) }}
    {{- $_ := set $rateLimiting "GeneralRules" (.Values.api.config.rateLimiting.generalRules | default $defaultAppSettings.IpRateLimiting.GeneralRules) }}
    {{- $_ := set $appSettings "IpRateLimiting" $rateLimiting }}
    {{- $appSettings | toJson | nindent 4 }}

  bingus_config.json: |
    {{- $bingusConfig := dict }}
    {{- $_ := set $bingusConfig "encoder_type" (.Values.api.config.bingus.encoderType | default $defaultBingusConfig.encoder_type) }}
    {{- $_ := set $bingusConfig "use_model_path" (.Values.api.config.bingus.useModelPath | default $defaultBingusConfig.use_model_path) }}
    {{- $_ := set $bingusConfig "api_uri" (.Values.api.config.bingus.apiUri | default $defaultBingusConfig.api_uri) }}
    {{- $_ := set $bingusConfig "llama_model_path" (.Values.api.config.bingus.llamaModelPath | default $defaultBingusConfig.llama_model_path) }}
    {{- $_ := set $bingusConfig "hnsw_seed" (.Values.api.config.bingus.hnswSeed | default $defaultBingusConfig.hnsw_seed) }}
    {{- $_ := set $bingusConfig "use_q2a" (.Values.api.config.bingus.useQ2a | default $defaultBingusConfig.use_q2a) }}
    {{- $bingusConfig | toJson | nindent 4 }}
{{- end }}
